logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{15} - %msg%n'
  file:
    name: application.log
    path: E:\IDEA\idea\mulu\my-logrequest
  level:
    root: info
    sql: info
    web: info