spring:
  log-boot:
    log-file-name: "application.log"
    log-path: "E:/IDEA/idea/mulu/my-logrequest"
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{15} - %msg%n"
    log-level: "INFO"
